services:
  - type: web
    name: peluqueria-system
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: mi_clave_secreta_super_segura_para_peluqueria_2024
    healthCheckPath: /health